### ISSUE TITLE
DNS servers from Swiss Privacy Foundation

### ISSUE THREAD

**Issue by cubit9-danielpeyer** [vermaden/network#1]
The DNS servers from Swiss Privacy Foundation (77.109.138.45 und 77.109.139.29) are turned off.
(More info here: https://privacyfoundation.ch/de/aktuelles/neue-ip-adressen-f%C3%BCr-dns-server.html)

You could add this new ones:

IPv4: 185.95.218.42
IPv6: 2a05:fc84::42
Servername: dns.digitale-gesellschaft.ch

IPv4: 185.95.218.43
IPv6: 2a05:fc84::43
Servername: dns.digitale-gesellschaft.ch

**Comment by vermaden** [comment]
Updated: https://github.com/vermaden/network/commit/655d6d9e59cf4134cac1a846bcfbe2aac8ff9f64

Thanks for good suggestion.

Regards :)

**Comment by cubit9-danielpeyer** [comment]
Thanks to you for sharing your knowledge and helpful scripts.

**Comment by vermaden** [comment]
> Thanks to you for sharing your knowledge and helpful scripts.

It goes both ways.

By sharing them I got A LOT of useful input and good advice on how to make them even better :)

Regards.
